const HELPFUL_ASSISTANT_PROMPT = `You are a helpful assistant.`;
const HELPFUL_ASSISTANT_PROMPT_PRE_MESSAGE = ``;

export default HELPFUL_ASSISTANT_PROMPT;
export { HELPFUL_ASSISTANT_PROMPT, HELPFUL_ASSISTANT_PROMPT_PRE_MESSAGE };
